[package]
name = "gentest"
version = "0.1.0"
authors = ["Emil Sjölander <emil@visly.app>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
failure = "0.1"
fantoccini = "0.11.7"
futures = "0.1"
indicatif = "0.11"
json = "0.11.13"
log = "0.4"
proc-macro2 = "0.4"
quote = "0.6"
serde_json = "1"
syn = "0.15"
tokio = "0.1"
